#!/bin/sh
if test "$verbose" = yes; then
  echo "runtest: $cc $ccflags ${ccout}tst$exe $* $cclibs" 
	$cc $ccflags ${ccout}tst$exe $* $cclibs 
else
  $cc $ccflags ${ccout}tst$exe $* $cclibs > /dev/null 2> /dev/null || exit 100
fi
exec ./tst$exe
